version: "3.7"

services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    container_name: ora-hydric
    ports:
      - 8091:8091
    volumes:
      - .:/usr/app
